// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7fvVzteIG5t_vgUiw8netiVaanu33e60',
    appId: '1:1010550848274:web:f7661a6a7a4279a54c51cb',
    messagingSenderId: '1010550848274',
    projectId: 'antrianq',
    authDomain: 'antrianq.firebaseapp.com',
    storageBucket: 'antrianq.firebasestorage.app',
    measurementId: 'G-6GYQHRWHVV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMBzAnbhnhvboNALc-ipRSb6O9g5IY0Cg',
    appId: '1:1010550848274:android:9586d3f856d15a7e4c51cb',
    messagingSenderId: '1010550848274',
    projectId: 'antrianq',
    storageBucket: 'antrianq.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBygLg85i2G-g9WCpLPtMvLosltecgVU4',
    appId: '1:1010550848274:ios:22903768b1ae5a884c51cb',
    messagingSenderId: '1010550848274',
    projectId: 'antrianq',
    storageBucket: 'antrianq.firebasestorage.app',
    iosBundleId: 'com.kholiq.antrianq',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBygLg85i2G-g9WCpLPtMvLosltecgVU4',
    appId: '1:1010550848274:ios:22903768b1ae5a884c51cb',
    messagingSenderId: '1010550848274',
    projectId: 'antrianq',
    storageBucket: 'antrianq.firebasestorage.app',
    iosBundleId: 'com.kholiq.antrianq',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7fvVzteIG5t_vgUiw8netiVaanu33e60',
    appId: '1:1010550848274:web:1e9e7d7c37fb7f8c4c51cb',
    messagingSenderId: '1010550848274',
    projectId: 'antrianq',
    authDomain: 'antrianq.firebaseapp.com',
    storageBucket: 'antrianq.firebasestorage.app',
    measurementId: 'G-ZEW8D542WD',
  );
}
